### ISSUE TITLE
register a MozActivity to display position from other apps 

### ISSUE THREAD

**Issue by EdoPut** [moimael/openmaps#1]
A very powerful way of integrating in the Firefox OS system is providing a [webActivity][mozActivity] to let other apps call yours, i.e. the contacts apps can request a call from the telephone app.

Yours is a truly wonderful app  but it would be exponentially better if the entire ecosystem would be able to access it.

You can find informations about how to register a mozActivity [here][register_activity].

[mozActivity]: https://developer.mozilla.org/en-US/docs/Web/API/MozActivity
[register_activity]: https://developer.mozilla.org/en-US/docs/Web/API/MozActivityRequestHandler

**Comment by moimael** [comment]
Thanks a lot for your feedback (the first ;))
Indeed this is interesting, I will try to integrate this for the current soon to be released openmaps !

Thanks again !

**Comment by EdoPut** [comment]
Given that I would really like to see this happen here are some things I thought were interesting:
```
"activities": {
    "name": "view",
    "filter": {
      "type": "map",
      "required": "position"
    }
...
```

requires at least a position object ({lat, lon}) and can draw a text overlay if "overlay" is provided.

This way we can have other apps provide something more than only a position.

Thanks again for your work! :)

**Comment by moimael** [comment]
I can't find precise informations on how to register a map type app. 

For now icame up with this in my manifest : 
```
  "activities": {
    "view": {
      "href": "./index.html",
      "disposition": "window",
      "filter": {
        "type": "map",
        "required": "position"
      }
    }
```

**Comment by EdoPut** [comment]
The manifest looks good to me, maybe the disposition should be "inlined" so that closing/click back return to the app that launched the activity.

I think we can extend the position filter some more to have lat, lon required
> But I'm not sure how to handle data that is passed and flters are a bit obscure since it's free form text..

It's a matter of taking care with

```
navigator.mozSetMessageHandler('activity', function (activityRequest) {
    // activityRequest.source contains a reference to the data from the callee
    // in activityRequest.source.data;
    var option = activityRequest.source;
   // let's say I want to access the position input
   var position = option.position;
});
```

You can have this code everywhere but it will only be executed on a activityRequest.

> Plus I can't find any apps that require to display data in a map app.

If this map activity were already integrated in Gaia I  would have gladly used it in my apps; e.g. Display the nearest bus stop on a map, display the tap water funtains ... but unfortunately it's not there

**Comment by moimael** [comment]
I just pushed the change, feel free to comment or improve it !

Thanks !

**Comment by moimael** [comment]
Have you had the chance to try it now that it's public on the marketplace ?

**Comment by EdoPut** [comment]
I will definitely try it use it from my apps, I have a barebone one that I use to test webActivities and I can call your app but it will show my position not the one I provide.

latlng should be what precisely? a string or a dict?


![schermata da 2015-10-20 21 31 48](https://cloud.githubusercontent.com/assets/4076473/10618753/16729926-7772-11e5-8e92-8e30cf9d3d2b.png)

**Comment by moimael** [comment]
just an array: [lat, lng]

**Comment by EdoPut** [comment]
Wooo! It's working! thank you so much, you saved me a lot of work :smile:

![schermata da 2015-10-25 11 27 59](https://cloud.githubusercontent.com/assets/4076473/10715168/c9b13a6e-7b0b-11e5-908a-c486f907661b.png)

**Comment by moimael** [comment]
np ;) Happy to see it working :)
